FROM centos:6
MAINTAINER Cha Jae Mun "amunsen@gmail.com"

RUN curl -O 'https://packages.chef.io/files/stable/chef/12.19.36/el/6/chef-12.19.36-1.el6.x86_64.rpm' -s
RUN rpm -ihv chef-12.19.36-1.el6.x86_64.rpm
RUN rm -f chef-12.19.36-1.el6.x86_64.rpm
